// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pushupes/v1/events.proto

package pushupesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_Append_FullMethodName        = "/pushupes.v1.EventService/Append"
	EventService_ReadStream_FullMethodName    = "/pushupes.v1.EventService/ReadStream"
	EventService_ReadTails_FullMethodName     = "/pushupes.v1.EventService/ReadTails"
	EventService_ReadByCommand_FullMethodName = "/pushupes.v1.EventService/ReadByCommand"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService is the client-facing data plane: event writes and event
// queries, served on its own port, independent of the HTTP admin/replication
// plane. Semantics mirror the JSON API (DESIGN.md): command_id idempotency,
// version = tail+1, reads observe <=HW, MOVED/ASK redirects carry the
// authoritative slot + node.
type EventServiceClient interface {
	// Append appends one record to one aggregate stream.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// ReadStream reads a version range of one aggregate stream.
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
	// ReadTails reports the latest version of many aggregates in one call.
	ReadTails(ctx context.Context, in *ReadTailsRequest, opts ...grpc.CallOption) (*ReadTailsResponse, error)
	// ReadByCommand looks one record up by command_id (idempotency probe).
	ReadByCommand(ctx context.Context, in *ReadByCommandRequest, opts ...grpc.CallOption) (*ReadByCommandResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, EventService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, EventService_ReadStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ReadTails(ctx context.Context, in *ReadTailsRequest, opts ...grpc.CallOption) (*ReadTailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTailsResponse)
	err := c.cc.Invoke(ctx, EventService_ReadTails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ReadByCommand(ctx context.Context, in *ReadByCommandRequest, opts ...grpc.CallOption) (*ReadByCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadByCommandResponse)
	err := c.cc.Invoke(ctx, EventService_ReadByCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService is the client-facing data plane: event writes and event
// queries, served on its own port, independent of the HTTP admin/replication
// plane. Semantics mirror the JSON API (DESIGN.md): command_id idempotency,
// version = tail+1, reads observe <=HW, MOVED/ASK redirects carry the
// authoritative slot + node.
type EventServiceServer interface {
	// Append appends one record to one aggregate stream.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// ReadStream reads a version range of one aggregate stream.
	ReadStream(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	// ReadTails reports the latest version of many aggregates in one call.
	ReadTails(context.Context, *ReadTailsRequest) (*ReadTailsResponse, error)
	// ReadByCommand looks one record up by command_id (idempotency probe).
	ReadByCommand(context.Context, *ReadByCommandRequest) (*ReadByCommandResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEventServiceServer) ReadStream(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadStream not implemented")
}
func (UnimplementedEventServiceServer) ReadTails(context.Context, *ReadTailsRequest) (*ReadTailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadTails not implemented")
}
func (UnimplementedEventServiceServer) ReadByCommand(context.Context, *ReadByCommandRequest) (*ReadByCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadByCommand not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ReadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ReadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ReadStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ReadStream(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ReadTails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ReadTails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ReadTails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ReadTails(ctx, req.(*ReadTailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ReadByCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ReadByCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ReadByCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ReadByCommand(ctx, req.(*ReadByCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pushupes.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EventService_Append_Handler,
		},
		{
			MethodName: "ReadStream",
			Handler:    _EventService_ReadStream_Handler,
		},
		{
			MethodName: "ReadTails",
			Handler:    _EventService_ReadTails_Handler,
		},
		{
			MethodName: "ReadByCommand",
			Handler:    _EventService_ReadByCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pushupes/v1/events.proto",
}
