// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pushupes/v1/events.proto

package pushupesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendResponse_Status int32

const (
	AppendResponse_STATUS_UNSPECIFIED AppendResponse_Status = 0
	AppendResponse_STATUS_SUCCESS     AppendResponse_Status = 1
	AppendResponse_STATUS_EXISTS      AppendResponse_Status = 2 // idempotent duplicate; record carries the stored entry
	AppendResponse_STATUS_FAIL        AppendResponse_Status = 3
)

// Enum value maps for AppendResponse_Status.
var (
	AppendResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_EXISTS",
		3: "STATUS_FAIL",
	}
	AppendResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_EXISTS":      2,
		"STATUS_FAIL":        3,
	}
)

func (x AppendResponse_Status) Enum() *AppendResponse_Status {
	p := new(AppendResponse_Status)
	*p = x
	return p
}

func (x AppendResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppendResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pushupes_v1_events_proto_enumTypes[0].Descriptor()
}

func (AppendResponse_Status) Type() protoreflect.EnumType {
	return &file_pushupes_v1_events_proto_enumTypes[0]
}

func (x AppendResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppendResponse_Status.Descriptor instead.
func (AppendResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{3, 0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // raw payload bytes (no JSON/base64 layering)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pushupes_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Record is one stored event-stream entry.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UnixTime      int64                  `protobuf:"varint,3,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	CommandId     string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"` // slot sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pushupes_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Record) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Record) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Record) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Record) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Record) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                     // must be stream tail + 1
	UnixTime      int64                  `protobuf:"varint,3,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`   // 0 = server clock
	CommandId     string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // idempotency key
	Events        []*Event               `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *AppendRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendRequest) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *AppendRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AppendRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AppendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         AppendResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=pushupes.v1.AppendResponse_Status" json:"status,omitempty"`
	ErrId          uint32                 `protobuf:"varint,2,opt,name=err_id,json=errId,proto3" json:"err_id,omitempty"` // wire error table: 1001 conflict, 1003 MOVED, 1004 ASK...
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CurrentVersion uint32                 `protobuf:"varint,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // set on 1001 for client self-heal
	Seq            uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	Slot           int32                  `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`    // routing slot (authoritative even on redirects)
	Node           string                 `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`     // redirect target "host:port" for MOVED/ASK/NOT_LEADER
	Record         *Record                `protobuf:"bytes,8,opt,name=record,proto3" json:"record,omitempty"` // set on STATUS_EXISTS only (the stored duplicate)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *AppendResponse) GetStatus() AppendResponse_Status {
	if x != nil {
		return x.Status
	}
	return AppendResponse_STATUS_UNSPECIFIED
}

func (x *AppendResponse) GetErrId() uint32 {
	if x != nil {
		return x.ErrId
	}
	return 0
}

func (x *AppendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppendResponse) GetCurrentVersion() uint32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *AppendResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AppendResponse) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AppendResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AppendResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// BatchAppendRequest carries a batch of appends. No size cap: the only bound
// is the gRPC message limit, which the operator configures
// (-grpc-max-msg-size, default 4MiB). An empty batch returns empty results.
type BatchAppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AppendRequest       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAppendRequest) Reset() {
	*x = BatchAppendRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAppendRequest) ProtoMessage() {}

func (x *BatchAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAppendRequest.ProtoReflect.Descriptor instead.
func (*BatchAppendRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *BatchAppendRequest) GetRecords() []*AppendRequest {
	if x != nil {
		return x.Records
	}
	return nil
}

// BatchAppendResult pairs one aggregate with its append outcome.
// aggregate_id echoes the request field so a result can be identified without
// positional assumptions; response mirrors single Append exactly
// (status/err_id/current_version/seq/slot/node/record).
type BatchAppendResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Response      *AppendResponse        `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAppendResult) Reset() {
	*x = BatchAppendResult{}
	mi := &file_pushupes_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAppendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAppendResult) ProtoMessage() {}

func (x *BatchAppendResult) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAppendResult.ProtoReflect.Descriptor instead.
func (*BatchAppendResult) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *BatchAppendResult) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *BatchAppendResult) GetResponse() *AppendResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

// BatchAppendResponse answers one result per request record, in the SAME
// ORDER as BatchAppendRequest.records.
type BatchAppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchAppendResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAppendResponse) Reset() {
	*x = BatchAppendResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAppendResponse) ProtoMessage() {}

func (x *BatchAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAppendResponse.ProtoReflect.Descriptor instead.
func (*BatchAppendResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *BatchAppendResponse) GetResults() []*BatchAppendResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	FromVersion   uint32                 `protobuf:"varint,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"` // 0 = 1
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                // 0 = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ReadStreamRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *ReadStreamRequest) GetFromVersion() uint32 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *ReadStreamRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextVersion   uint32                 `protobuf:"varint,2,opt,name=next_version,json=nextVersion,proto3" json:"next_version,omitempty"`
	LastVersion   uint32                 `protobuf:"varint,3,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamResponse) Reset() {
	*x = ReadStreamResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamResponse) ProtoMessage() {}

func (x *ReadStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamResponse.ProtoReflect.Descriptor instead.
func (*ReadStreamResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *ReadStreamResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ReadStreamResponse) GetNextVersion() uint32 {
	if x != nil {
		return x.NextVersion
	}
	return 0
}

func (x *ReadStreamResponse) GetLastVersion() uint32 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

// ReadTailsRequest asks for the latest version of each listed aggregate.
type ReadTailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateIds  []string               `protobuf:"bytes,1,rep,name=aggregate_ids,json=aggregateIds,proto3" json:"aggregate_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTailsRequest) Reset() {
	*x = ReadTailsRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTailsRequest) ProtoMessage() {}

func (x *ReadTailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTailsRequest.ProtoReflect.Descriptor instead.
func (*ReadTailsRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *ReadTailsRequest) GetAggregateIds() []string {
	if x != nil {
		return x.AggregateIds
	}
	return nil
}

// ReadTailsResponse answers with one version per requested aggregate, in the
// SAME ORDER as the request: versions[i] is the tail of aggregate_ids[i], and
// 0 means that aggregate has no records in the slot the answering node holds.
//
// This is the bulk form of "does version k exist" probing: a resume scan needs
// one number per aggregate, and one RPC per aggregate made the scan cost grow
// with the number of streams. The bound is the same one ReadStream applies —
// the answering node's own durable LEO (never a stale former-leader
// watermark), same as ReadStream.
type ReadTailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []uint32               `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTailsResponse) Reset() {
	*x = ReadTailsResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTailsResponse) ProtoMessage() {}

func (x *ReadTailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTailsResponse.ProtoReflect.Descriptor instead.
func (*ReadTailsResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReadTailsResponse) GetVersions() []uint32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ReadByCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadByCommandRequest) Reset() {
	*x = ReadByCommandRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadByCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadByCommandRequest) ProtoMessage() {}

func (x *ReadByCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadByCommandRequest.ProtoReflect.Descriptor instead.
func (*ReadByCommandRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *ReadByCommandRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *ReadByCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ReadByCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadByCommandResponse) Reset() {
	*x = ReadByCommandResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadByCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadByCommandResponse) ProtoMessage() {}

func (x *ReadByCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadByCommandResponse.ProtoReflect.Descriptor instead.
func (*ReadByCommandResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *ReadByCommandResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReadByCommandResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// ReadVersionByTimeRequest asks for the point-in-time version anchor of one
// aggregate: the highest version whose record carries unix_time less than or
// equal to unix_time (a record stamped exactly at the queried time is the
// answer). A stream with no record visible at or before that time answers 0.
type ReadVersionByTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	UnixTime      int64                  `protobuf:"varint,2,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVersionByTimeRequest) Reset() {
	*x = ReadVersionByTimeRequest{}
	mi := &file_pushupes_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVersionByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVersionByTimeRequest) ProtoMessage() {}

func (x *ReadVersionByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVersionByTimeRequest.ProtoReflect.Descriptor instead.
func (*ReadVersionByTimeRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *ReadVersionByTimeRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *ReadVersionByTimeRequest) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type ReadVersionByTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 0 = no record visible at or before the time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVersionByTimeResponse) Reset() {
	*x = ReadVersionByTimeResponse{}
	mi := &file_pushupes_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVersionByTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVersionByTimeResponse) ProtoMessage() {}

func (x *ReadVersionByTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVersionByTimeResponse.ProtoReflect.Descriptor instead.
func (*ReadVersionByTimeResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *ReadVersionByTimeResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_pushupes_v1_events_proto protoreflect.FileDescriptor

const file_pushupes_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18pushupes/v1/events.proto\x12\vpushupes.v1\"/\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\xbf\x01\n" +
	"\x06Record\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1b\n" +
	"\tunix_time\x18\x03 \x01(\x03R\bunixTime\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\x12*\n" +
	"\x06events\x18\x05 \x03(\v2\x12.pushupes.v1.EventR\x06events\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\"\xba\x01\n" +
	"\rAppendRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1b\n" +
	"\tunix_time\x18\x03 \x01(\x03R\bunixTime\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\x12*\n" +
	"\x06events\x18\x05 \x03(\v2\x12.pushupes.v1.EventR\x06eventsJ\x04\b\x06\x10\a\"\xe7\x02\n" +
	"\x0eAppendResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".pushupes.v1.AppendResponse.StatusR\x06status\x12\x15\n" +
	"\x06err_id\x18\x02 \x01(\rR\x05errId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\rR\x0ecurrentVersion\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04node\x18\a \x01(\tR\x04node\x12+\n" +
	"\x06record\x18\b \x01(\v2\x13.pushupes.v1.RecordR\x06record\"X\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x11\n" +
	"\rSTATUS_EXISTS\x10\x02\x12\x0f\n" +
	"\vSTATUS_FAIL\x10\x03\"J\n" +
	"\x12BatchAppendRequest\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.pushupes.v1.AppendRequestR\arecords\"o\n" +
	"\x11BatchAppendResult\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x127\n" +
	"\bresponse\x18\x02 \x01(\v2\x1b.pushupes.v1.AppendResponseR\bresponse\"O\n" +
	"\x13BatchAppendResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.pushupes.v1.BatchAppendResultR\aresults\"o\n" +
	"\x11ReadStreamRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\rR\vfromVersion\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"\x89\x01\n" +
	"\x12ReadStreamResponse\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.pushupes.v1.RecordR\arecords\x12!\n" +
	"\fnext_version\x18\x02 \x01(\rR\vnextVersion\x12!\n" +
	"\flast_version\x18\x03 \x01(\rR\vlastVersion\"7\n" +
	"\x10ReadTailsRequest\x12#\n" +
	"\raggregate_ids\x18\x01 \x03(\tR\faggregateIds\"/\n" +
	"\x11ReadTailsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\rR\bversions\"X\n" +
	"\x14ReadByCommandRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\"Z\n" +
	"\x15ReadByCommandResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x06record\x18\x02 \x01(\v2\x13.pushupes.v1.RecordR\x06record\"Z\n" +
	"\x18ReadVersionByTimeRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12\x1b\n" +
	"\tunix_time\x18\x02 \x01(\x03R\bunixTime\"5\n" +
	"\x19ReadVersionByTimeResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion2\xfa\x03\n" +
	"\fEventService\x12A\n" +
	"\x06Append\x12\x1a.pushupes.v1.AppendRequest\x1a\x1b.pushupes.v1.AppendResponse\x12P\n" +
	"\vBatchAppend\x12\x1f.pushupes.v1.BatchAppendRequest\x1a .pushupes.v1.BatchAppendResponse\x12M\n" +
	"\n" +
	"ReadStream\x12\x1e.pushupes.v1.ReadStreamRequest\x1a\x1f.pushupes.v1.ReadStreamResponse\x12J\n" +
	"\tReadTails\x12\x1d.pushupes.v1.ReadTailsRequest\x1a\x1e.pushupes.v1.ReadTailsResponse\x12V\n" +
	"\rReadByCommand\x12!.pushupes.v1.ReadByCommandRequest\x1a\".pushupes.v1.ReadByCommandResponse\x12b\n" +
	"\x11ReadVersionByTime\x12%.pushupes.v1.ReadVersionByTimeRequest\x1a&.pushupes.v1.ReadVersionByTimeResponseB2Z0pushupes/internal/grpcapi/pushupes/v1;pushupesv1b\x06proto3"

var (
	file_pushupes_v1_events_proto_rawDescOnce sync.Once
	file_pushupes_v1_events_proto_rawDescData []byte
)

func file_pushupes_v1_events_proto_rawDescGZIP() []byte {
	file_pushupes_v1_events_proto_rawDescOnce.Do(func() {
		file_pushupes_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pushupes_v1_events_proto_rawDesc), len(file_pushupes_v1_events_proto_rawDesc)))
	})
	return file_pushupes_v1_events_proto_rawDescData
}

var file_pushupes_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pushupes_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pushupes_v1_events_proto_goTypes = []any{
	(AppendResponse_Status)(0),        // 0: pushupes.v1.AppendResponse.Status
	(*Event)(nil),                     // 1: pushupes.v1.Event
	(*Record)(nil),                    // 2: pushupes.v1.Record
	(*AppendRequest)(nil),             // 3: pushupes.v1.AppendRequest
	(*AppendResponse)(nil),            // 4: pushupes.v1.AppendResponse
	(*BatchAppendRequest)(nil),        // 5: pushupes.v1.BatchAppendRequest
	(*BatchAppendResult)(nil),         // 6: pushupes.v1.BatchAppendResult
	(*BatchAppendResponse)(nil),       // 7: pushupes.v1.BatchAppendResponse
	(*ReadStreamRequest)(nil),         // 8: pushupes.v1.ReadStreamRequest
	(*ReadStreamResponse)(nil),        // 9: pushupes.v1.ReadStreamResponse
	(*ReadTailsRequest)(nil),          // 10: pushupes.v1.ReadTailsRequest
	(*ReadTailsResponse)(nil),         // 11: pushupes.v1.ReadTailsResponse
	(*ReadByCommandRequest)(nil),      // 12: pushupes.v1.ReadByCommandRequest
	(*ReadByCommandResponse)(nil),     // 13: pushupes.v1.ReadByCommandResponse
	(*ReadVersionByTimeRequest)(nil),  // 14: pushupes.v1.ReadVersionByTimeRequest
	(*ReadVersionByTimeResponse)(nil), // 15: pushupes.v1.ReadVersionByTimeResponse
}
var file_pushupes_v1_events_proto_depIdxs = []int32{
	1,  // 0: pushupes.v1.Record.events:type_name -> pushupes.v1.Event
	1,  // 1: pushupes.v1.AppendRequest.events:type_name -> pushupes.v1.Event
	0,  // 2: pushupes.v1.AppendResponse.status:type_name -> pushupes.v1.AppendResponse.Status
	2,  // 3: pushupes.v1.AppendResponse.record:type_name -> pushupes.v1.Record
	3,  // 4: pushupes.v1.BatchAppendRequest.records:type_name -> pushupes.v1.AppendRequest
	4,  // 5: pushupes.v1.BatchAppendResult.response:type_name -> pushupes.v1.AppendResponse
	6,  // 6: pushupes.v1.BatchAppendResponse.results:type_name -> pushupes.v1.BatchAppendResult
	2,  // 7: pushupes.v1.ReadStreamResponse.records:type_name -> pushupes.v1.Record
	2,  // 8: pushupes.v1.ReadByCommandResponse.record:type_name -> pushupes.v1.Record
	3,  // 9: pushupes.v1.EventService.Append:input_type -> pushupes.v1.AppendRequest
	5,  // 10: pushupes.v1.EventService.BatchAppend:input_type -> pushupes.v1.BatchAppendRequest
	8,  // 11: pushupes.v1.EventService.ReadStream:input_type -> pushupes.v1.ReadStreamRequest
	10, // 12: pushupes.v1.EventService.ReadTails:input_type -> pushupes.v1.ReadTailsRequest
	12, // 13: pushupes.v1.EventService.ReadByCommand:input_type -> pushupes.v1.ReadByCommandRequest
	14, // 14: pushupes.v1.EventService.ReadVersionByTime:input_type -> pushupes.v1.ReadVersionByTimeRequest
	4,  // 15: pushupes.v1.EventService.Append:output_type -> pushupes.v1.AppendResponse
	7,  // 16: pushupes.v1.EventService.BatchAppend:output_type -> pushupes.v1.BatchAppendResponse
	9,  // 17: pushupes.v1.EventService.ReadStream:output_type -> pushupes.v1.ReadStreamResponse
	11, // 18: pushupes.v1.EventService.ReadTails:output_type -> pushupes.v1.ReadTailsResponse
	13, // 19: pushupes.v1.EventService.ReadByCommand:output_type -> pushupes.v1.ReadByCommandResponse
	15, // 20: pushupes.v1.EventService.ReadVersionByTime:output_type -> pushupes.v1.ReadVersionByTimeResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pushupes_v1_events_proto_init() }
func file_pushupes_v1_events_proto_init() {
	if File_pushupes_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pushupes_v1_events_proto_rawDesc), len(file_pushupes_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pushupes_v1_events_proto_goTypes,
		DependencyIndexes: file_pushupes_v1_events_proto_depIdxs,
		EnumInfos:         file_pushupes_v1_events_proto_enumTypes,
		MessageInfos:      file_pushupes_v1_events_proto_msgTypes,
	}.Build()
	File_pushupes_v1_events_proto = out.File
	file_pushupes_v1_events_proto_goTypes = nil
	file_pushupes_v1_events_proto_depIdxs = nil
}
