// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pushupes/v1/peer.proto

package pushupesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerService_Ping_FullMethodName            = "/pushupes.v1.PeerService/Ping"
	PeerService_Register_FullMethodName        = "/pushupes.v1.PeerService/Register"
	PeerService_MFetch_FullMethodName          = "/pushupes.v1.PeerService/MFetch"
	PeerService_ReplicaProgress_FullMethodName = "/pushupes.v1.PeerService/ReplicaProgress"
	PeerService_Replicate_FullMethodName       = "/pushupes.v1.PeerService/Replicate"
	PeerService_SlotLeo_FullMethodName         = "/pushupes.v1.PeerService/SlotLeo"
	PeerService_PushSegments_FullMethodName    = "/pushupes.v1.PeerService/PushSegments"
	PeerService_TriggerSnapshot_FullMethodName = "/pushupes.v1.PeerService/TriggerSnapshot"
)

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PeerService is the inter-node data plane. It is served on the SAME port
// as the Raft transport (the peer port): the connection demux routes the
// HTTP/2 preface (first byte 'P') here and every other first byte to
// Raft. All node-to-node communication — replication fetch, LEO progress,
// migration forwarding/segments/snapshot, liveness probing and address
// registration — rides this one gRPC surface; the admin port is
// management-only.
type PeerServiceClient interface {
	// Ping is the liveness probe (controller failover).
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Register announces a node's admin/client addresses into the routing
	// table (leader commits an OpRegister; non-leaders relay).
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// MFetch is the multiplexed replica fetch: every slot this follower
	// copies from the serving leader is one item; the call long-polls when
	// everything is empty (wait_ms budget, server-held).
	MFetch(ctx context.Context, in *MFetchRequest, opts ...grpc.CallOption) (*MFetchResponse, error)
	// ReplicaProgress reports follower LEOs in bulk after a productive round.
	ReplicaProgress(ctx context.Context, in *ReplicaProgressRequest, opts ...grpc.CallOption) (*ReplicaProgressResponse, error)
	// Replicate pushes one leader-assigned record to the migration target
	// during the forwarding window (idempotent at seq).
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
	// SlotLeo answers a single slot's log end offset (migration catch-up).
	SlotLeo(ctx context.Context, in *SlotLeoRequest, opts ...grpc.CallOption) (*SlotLeoResponse, error)
	// PushSegments streams sealed WAL segments of a slot into the importing
	// node (migration snapshot step; messages are whole files).
	PushSegments(ctx context.Context, in *PushSegmentsRequest, opts ...grpc.CallOption) (*PushSegmentsResponse, error)
	// TriggerSnapshot asks this node, as migration source, to push its
	// sealed segments of a slot to the target.
	TriggerSnapshot(ctx context.Context, in *TriggerSnapshotRequest, opts ...grpc.CallOption) (*TriggerSnapshotResponse, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, PeerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PeerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) MFetch(ctx context.Context, in *MFetchRequest, opts ...grpc.CallOption) (*MFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFetchResponse)
	err := c.cc.Invoke(ctx, PeerService_MFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ReplicaProgress(ctx context.Context, in *ReplicaProgressRequest, opts ...grpc.CallOption) (*ReplicaProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaProgressResponse)
	err := c.cc.Invoke(ctx, PeerService_ReplicaProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, PeerService_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) SlotLeo(ctx context.Context, in *SlotLeoRequest, opts ...grpc.CallOption) (*SlotLeoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotLeoResponse)
	err := c.cc.Invoke(ctx, PeerService_SlotLeo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) PushSegments(ctx context.Context, in *PushSegmentsRequest, opts ...grpc.CallOption) (*PushSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushSegmentsResponse)
	err := c.cc.Invoke(ctx, PeerService_PushSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) TriggerSnapshot(ctx context.Context, in *TriggerSnapshotRequest, opts ...grpc.CallOption) (*TriggerSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerSnapshotResponse)
	err := c.cc.Invoke(ctx, PeerService_TriggerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility.
//
// PeerService is the inter-node data plane. It is served on the SAME port
// as the Raft transport (the peer port): the connection demux routes the
// HTTP/2 preface (first byte 'P') here and every other first byte to
// Raft. All node-to-node communication — replication fetch, LEO progress,
// migration forwarding/segments/snapshot, liveness probing and address
// registration — rides this one gRPC surface; the admin port is
// management-only.
type PeerServiceServer interface {
	// Ping is the liveness probe (controller failover).
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Register announces a node's admin/client addresses into the routing
	// table (leader commits an OpRegister; non-leaders relay).
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// MFetch is the multiplexed replica fetch: every slot this follower
	// copies from the serving leader is one item; the call long-polls when
	// everything is empty (wait_ms budget, server-held).
	MFetch(context.Context, *MFetchRequest) (*MFetchResponse, error)
	// ReplicaProgress reports follower LEOs in bulk after a productive round.
	ReplicaProgress(context.Context, *ReplicaProgressRequest) (*ReplicaProgressResponse, error)
	// Replicate pushes one leader-assigned record to the migration target
	// during the forwarding window (idempotent at seq).
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	// SlotLeo answers a single slot's log end offset (migration catch-up).
	SlotLeo(context.Context, *SlotLeoRequest) (*SlotLeoResponse, error)
	// PushSegments streams sealed WAL segments of a slot into the importing
	// node (migration snapshot step; messages are whole files).
	PushSegments(context.Context, *PushSegmentsRequest) (*PushSegmentsResponse, error)
	// TriggerSnapshot asks this node, as migration source, to push its
	// sealed segments of a slot to the target.
	TriggerSnapshot(context.Context, *TriggerSnapshotRequest) (*TriggerSnapshotResponse, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerServiceServer struct{}

func (UnimplementedPeerServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPeerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPeerServiceServer) MFetch(context.Context, *MFetchRequest) (*MFetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MFetch not implemented")
}
func (UnimplementedPeerServiceServer) ReplicaProgress(context.Context, *ReplicaProgressRequest) (*ReplicaProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicaProgress not implemented")
}
func (UnimplementedPeerServiceServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedPeerServiceServer) SlotLeo(context.Context, *SlotLeoRequest) (*SlotLeoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SlotLeo not implemented")
}
func (UnimplementedPeerServiceServer) PushSegments(context.Context, *PushSegmentsRequest) (*PushSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushSegments not implemented")
}
func (UnimplementedPeerServiceServer) TriggerSnapshot(context.Context, *TriggerSnapshotRequest) (*TriggerSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSnapshot not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}
func (UnimplementedPeerServiceServer) testEmbeddedByValue()                     {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	// If the following call panics, it indicates UnimplementedPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerService_ServiceDesc, srv)
}

func _PeerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_MFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).MFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_MFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).MFetch(ctx, req.(*MFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ReplicaProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ReplicaProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_ReplicaProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ReplicaProgress(ctx, req.(*ReplicaProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_SlotLeo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotLeoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).SlotLeo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_SlotLeo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).SlotLeo(ctx, req.(*SlotLeoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_PushSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).PushSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_PushSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).PushSegments(ctx, req.(*PushSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_TriggerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).TriggerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_TriggerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).TriggerSnapshot(ctx, req.(*TriggerSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerService_ServiceDesc is the grpc.ServiceDesc for PeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pushupes.v1.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PeerService_Ping_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _PeerService_Register_Handler,
		},
		{
			MethodName: "MFetch",
			Handler:    _PeerService_MFetch_Handler,
		},
		{
			MethodName: "ReplicaProgress",
			Handler:    _PeerService_ReplicaProgress_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _PeerService_Replicate_Handler,
		},
		{
			MethodName: "SlotLeo",
			Handler:    _PeerService_SlotLeo_Handler,
		},
		{
			MethodName: "PushSegments",
			Handler:    _PeerService_PushSegments_Handler,
		},
		{
			MethodName: "TriggerSnapshot",
			Handler:    _PeerService_TriggerSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pushupes/v1/peer.proto",
}
