// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pushupes/v1/peer.proto

package pushupesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminAddr     string                 `protobuf:"bytes,2,opt,name=admin_addr,json=adminAddr,proto3" json:"admin_addr,omitempty"`    // management HTTP base (scheme carried)
	ClientAddr    string                 `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"` // client-facing gRPC base (scheme carried)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetAdminAddr() string {
	if x != nil {
		return x.AdminAddr
	}
	return ""
}

func (x *RegisterRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{3}
}

// FetchItem: request entries fill slot/from_seq; response entries add
// next_seq/payload/leader_leo/leader_hw. payload is raw concatenated WAL
// record bytes (length-prefixed frames), never re-encoded.
type FetchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	NextSeq       uint64                 `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	LeaderLeo     uint64                 `protobuf:"varint,5,opt,name=leader_leo,json=leaderLeo,proto3" json:"leader_leo,omitempty"`
	LeaderHw      uint64                 `protobuf:"varint,6,opt,name=leader_hw,json=leaderHw,proto3" json:"leader_hw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItem) Reset() {
	*x = FetchItem{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItem) ProtoMessage() {}

func (x *FetchItem) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItem.ProtoReflect.Descriptor instead.
func (*FetchItem) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *FetchItem) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *FetchItem) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *FetchItem) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *FetchItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchItem) GetLeaderLeo() uint64 {
	if x != nil {
		return x.LeaderLeo
	}
	return 0
}

func (x *FetchItem) GetLeaderHw() uint64 {
	if x != nil {
		return x.LeaderHw
	}
	return 0
}

type MFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	WaitMs        int64                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	Items         []*FetchItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFetchRequest) Reset() {
	*x = MFetchRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFetchRequest) ProtoMessage() {}

func (x *MFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFetchRequest.ProtoReflect.Descriptor instead.
func (*MFetchRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{5}
}

func (x *MFetchRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *MFetchRequest) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *MFetchRequest) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Items         []*FetchItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFetchResponse) Reset() {
	*x = MFetchResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFetchResponse) ProtoMessage() {}

func (x *MFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFetchResponse.ProtoReflect.Descriptor instead.
func (*MFetchResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *MFetchResponse) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *MFetchResponse) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplicaProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Items         []*FetchItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // slot/from_seq carry the durable positions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaProgressRequest) Reset() {
	*x = ReplicaProgressRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaProgressRequest) ProtoMessage() {}

func (x *ReplicaProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaProgressRequest.ProtoReflect.Descriptor instead.
func (*ReplicaProgressRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicaProgressRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *ReplicaProgressRequest) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplicaProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaProgressResponse) Reset() {
	*x = ReplicaProgressResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaProgressResponse) ProtoMessage() {}

func (x *ReplicaProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaProgressResponse.ProtoReflect.Descriptor instead.
func (*ReplicaProgressResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{8}
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // one encoded record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicateRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReplicateRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReplicateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{10}
}

type SlotLeoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeoRequest) Reset() {
	*x = SlotLeoRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeoRequest) ProtoMessage() {}

func (x *SlotLeoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeoRequest.ProtoReflect.Descriptor instead.
func (*SlotLeoRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{11}
}

func (x *SlotLeoRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type SlotLeoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leo           uint64                 `protobuf:"varint,1,opt,name=leo,proto3" json:"leo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeoResponse) Reset() {
	*x = SlotLeoResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeoResponse) ProtoMessage() {}

func (x *SlotLeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeoResponse.ProtoReflect.Descriptor instead.
func (*SlotLeoResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{12}
}

func (x *SlotLeoResponse) GetLeo() uint64 {
	if x != nil {
		return x.Leo
	}
	return 0
}

// PushSegmentsChunk is one piece of the snapshot stream. The first chunk
// of a file carries its name and total size (header bytes included);
// following chunks carry data only. A new name starts a new file.
type PushSegmentsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // set on the first chunk of each segment file
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // total bytes of the file, set with name
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`  // file bytes; stream order, chunk sizes bounded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSegmentsChunk) Reset() {
	*x = PushSegmentsChunk{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSegmentsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentsChunk) ProtoMessage() {}

func (x *PushSegmentsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentsChunk.ProtoReflect.Descriptor instead.
func (*PushSegmentsChunk) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{13}
}

func (x *PushSegmentsChunk) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PushSegmentsChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PushSegmentsChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PushSegmentsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSegmentsResponse) Reset() {
	*x = PushSegmentsResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentsResponse) ProtoMessage() {}

func (x *PushSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentsResponse.ProtoReflect.Descriptor instead.
func (*PushSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{14}
}

type TriggerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerSnapshotRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TriggerSnapshotRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{16}
}

var File_pushupes_v1_peer_proto protoreflect.FileDescriptor

const file_pushupes_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x16pushupes/v1/peer.proto\x12\vpushupes.v1\"\r\n" +
	"\vPingRequest\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"a\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"admin_addr\x18\x02 \x01(\tR\tadminAddr\x12\x1f\n" +
	"\vclient_addr\x18\x03 \x01(\tR\n" +
	"clientAddr\"\x12\n" +
	"\x10RegisterResponse\"\xab\x01\n" +
	"\tFetchItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x04R\anextSeq\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"leader_leo\x18\x05 \x01(\x04R\tleaderLeo\x12\x1b\n" +
	"\tleader_hw\x18\x06 \x01(\x04R\bleaderHw\"r\n" +
	"\rMFetchRequest\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x03R\x06waitMs\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.pushupes.v1.FetchItemR\x05items\"Z\n" +
	"\x0eMFetchResponse\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.pushupes.v1.FetchItemR\x05items\"b\n" +
	"\x16ReplicaProgressRequest\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.pushupes.v1.FetchItemR\x05items\"\x19\n" +
	"\x17ReplicaProgressResponse\"R\n" +
	"\x10ReplicateRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x13\n" +
	"\x11ReplicateResponse\"$\n" +
	"\x0eSlotLeoRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"#\n" +
	"\x0fSlotLeoResponse\x12\x10\n" +
	"\x03leo\x18\x01 \x01(\x04R\x03leo\"c\n" +
	"\x11PushSegmentsChunk\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x16\n" +
	"\x14PushSegmentsResponse\"E\n" +
	"\x16TriggerSnapshotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\"\x19\n" +
	"\x17TriggerSnapshotResponse2\xf9\x04\n" +
	"\vPeerService\x12;\n" +
	"\x04Ping\x12\x18.pushupes.v1.PingRequest\x1a\x19.pushupes.v1.PingResponse\x12G\n" +
	"\bRegister\x12\x1c.pushupes.v1.RegisterRequest\x1a\x1d.pushupes.v1.RegisterResponse\x12A\n" +
	"\x06MFetch\x12\x1a.pushupes.v1.MFetchRequest\x1a\x1b.pushupes.v1.MFetchResponse\x12\\\n" +
	"\x0fReplicaProgress\x12#.pushupes.v1.ReplicaProgressRequest\x1a$.pushupes.v1.ReplicaProgressResponse\x12J\n" +
	"\tReplicate\x12\x1d.pushupes.v1.ReplicateRequest\x1a\x1e.pushupes.v1.ReplicateResponse\x12D\n" +
	"\aSlotLeo\x12\x1b.pushupes.v1.SlotLeoRequest\x1a\x1c.pushupes.v1.SlotLeoResponse\x12S\n" +
	"\fPushSegments\x12\x1e.pushupes.v1.PushSegmentsChunk\x1a!.pushupes.v1.PushSegmentsResponse(\x01\x12\\\n" +
	"\x0fTriggerSnapshot\x12#.pushupes.v1.TriggerSnapshotRequest\x1a$.pushupes.v1.TriggerSnapshotResponseB2Z0pushupes/internal/grpcapi/pushupes/v1;pushupesv1b\x06proto3"

var (
	file_pushupes_v1_peer_proto_rawDescOnce sync.Once
	file_pushupes_v1_peer_proto_rawDescData []byte
)

func file_pushupes_v1_peer_proto_rawDescGZIP() []byte {
	file_pushupes_v1_peer_proto_rawDescOnce.Do(func() {
		file_pushupes_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pushupes_v1_peer_proto_rawDesc), len(file_pushupes_v1_peer_proto_rawDesc)))
	})
	return file_pushupes_v1_peer_proto_rawDescData
}

var file_pushupes_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pushupes_v1_peer_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: pushupes.v1.PingRequest
	(*PingResponse)(nil),            // 1: pushupes.v1.PingResponse
	(*RegisterRequest)(nil),         // 2: pushupes.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 3: pushupes.v1.RegisterResponse
	(*FetchItem)(nil),               // 4: pushupes.v1.FetchItem
	(*MFetchRequest)(nil),           // 5: pushupes.v1.MFetchRequest
	(*MFetchResponse)(nil),          // 6: pushupes.v1.MFetchResponse
	(*ReplicaProgressRequest)(nil),  // 7: pushupes.v1.ReplicaProgressRequest
	(*ReplicaProgressResponse)(nil), // 8: pushupes.v1.ReplicaProgressResponse
	(*ReplicateRequest)(nil),        // 9: pushupes.v1.ReplicateRequest
	(*ReplicateResponse)(nil),       // 10: pushupes.v1.ReplicateResponse
	(*SlotLeoRequest)(nil),          // 11: pushupes.v1.SlotLeoRequest
	(*SlotLeoResponse)(nil),         // 12: pushupes.v1.SlotLeoResponse
	(*PushSegmentsChunk)(nil),       // 13: pushupes.v1.PushSegmentsChunk
	(*PushSegmentsResponse)(nil),    // 14: pushupes.v1.PushSegmentsResponse
	(*TriggerSnapshotRequest)(nil),  // 15: pushupes.v1.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil), // 16: pushupes.v1.TriggerSnapshotResponse
}
var file_pushupes_v1_peer_proto_depIdxs = []int32{
	4,  // 0: pushupes.v1.MFetchRequest.items:type_name -> pushupes.v1.FetchItem
	4,  // 1: pushupes.v1.MFetchResponse.items:type_name -> pushupes.v1.FetchItem
	4,  // 2: pushupes.v1.ReplicaProgressRequest.items:type_name -> pushupes.v1.FetchItem
	0,  // 3: pushupes.v1.PeerService.Ping:input_type -> pushupes.v1.PingRequest
	2,  // 4: pushupes.v1.PeerService.Register:input_type -> pushupes.v1.RegisterRequest
	5,  // 5: pushupes.v1.PeerService.MFetch:input_type -> pushupes.v1.MFetchRequest
	7,  // 6: pushupes.v1.PeerService.ReplicaProgress:input_type -> pushupes.v1.ReplicaProgressRequest
	9,  // 7: pushupes.v1.PeerService.Replicate:input_type -> pushupes.v1.ReplicateRequest
	11, // 8: pushupes.v1.PeerService.SlotLeo:input_type -> pushupes.v1.SlotLeoRequest
	13, // 9: pushupes.v1.PeerService.PushSegments:input_type -> pushupes.v1.PushSegmentsChunk
	15, // 10: pushupes.v1.PeerService.TriggerSnapshot:input_type -> pushupes.v1.TriggerSnapshotRequest
	1,  // 11: pushupes.v1.PeerService.Ping:output_type -> pushupes.v1.PingResponse
	3,  // 12: pushupes.v1.PeerService.Register:output_type -> pushupes.v1.RegisterResponse
	6,  // 13: pushupes.v1.PeerService.MFetch:output_type -> pushupes.v1.MFetchResponse
	8,  // 14: pushupes.v1.PeerService.ReplicaProgress:output_type -> pushupes.v1.ReplicaProgressResponse
	10, // 15: pushupes.v1.PeerService.Replicate:output_type -> pushupes.v1.ReplicateResponse
	12, // 16: pushupes.v1.PeerService.SlotLeo:output_type -> pushupes.v1.SlotLeoResponse
	14, // 17: pushupes.v1.PeerService.PushSegments:output_type -> pushupes.v1.PushSegmentsResponse
	16, // 18: pushupes.v1.PeerService.TriggerSnapshot:output_type -> pushupes.v1.TriggerSnapshotResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pushupes_v1_peer_proto_init() }
func file_pushupes_v1_peer_proto_init() {
	if File_pushupes_v1_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pushupes_v1_peer_proto_rawDesc), len(file_pushupes_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pushupes_v1_peer_proto_goTypes,
		DependencyIndexes: file_pushupes_v1_peer_proto_depIdxs,
		MessageInfos:      file_pushupes_v1_peer_proto_msgTypes,
	}.Build()
	File_pushupes_v1_peer_proto = out.File
	file_pushupes_v1_peer_proto_goTypes = nil
	file_pushupes_v1_peer_proto_depIdxs = nil
}
