// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pushupes/v1/peer.proto

package pushupesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminAddr     string                 `protobuf:"bytes,2,opt,name=admin_addr,json=adminAddr,proto3" json:"admin_addr,omitempty"`    // management HTTP base (scheme carried)
	ClientAddr    string                 `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"` // client-facing gRPC base (scheme carried)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetAdminAddr() string {
	if x != nil {
		return x.AdminAddr
	}
	return ""
}

func (x *RegisterRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{3}
}

// AdoptRequest is a node offering itself to the cluster. peer_addr is its
// consensus endpoint — the only address membership needs; admin/client
// addresses arrive later through the ordinary registration heartbeat.
type AdoptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeerAddr      string                 `protobuf:"bytes,2,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptRequest) Reset() {
	*x = AdoptRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptRequest) ProtoMessage() {}

func (x *AdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptRequest.ProtoReflect.Descriptor instead.
func (*AdoptRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *AdoptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdoptRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

type AdoptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptResponse) Reset() {
	*x = AdoptResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptResponse) ProtoMessage() {}

func (x *AdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptResponse.ProtoReflect.Descriptor instead.
func (*AdoptResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{5}
}

// FetchItem: response entries only (requests use packed parallel arrays in
// MFetchRequest). ReplicaProgress reuses slot/from_seq for durable positions.
// payload is raw concatenated WAL record bytes (length-prefixed frames),
// never re-encoded.
type FetchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	NextSeq       uint64                 `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItem) Reset() {
	*x = FetchItem{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItem) ProtoMessage() {}

func (x *FetchItem) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItem.ProtoReflect.Descriptor instead.
func (*FetchItem) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *FetchItem) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *FetchItem) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *FetchItem) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *FetchItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MFetchRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Follower string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	WaitMs   int64                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	// Packed parallel positions: slot[i] wanted from from_seqs[i].
	// Scalar arrays (not messages): a session carries every followed slot
	// each round, and per-entry FetchItem objects dominated the wire cost.
	Slots    []int32  `protobuf:"varint,3,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	FromSeqs []uint64 `protobuf:"varint,4,rep,packed,name=from_seqs,json=fromSeqs,proto3" json:"from_seqs,omitempty"`
	// sweep marks the periodic liveness round: the leader refreshes the
	// replica last-seen stamps for EVERY reported position. Ordinary rounds
	// record only positions that actually moved (see progressBatch.stamp).
	Sweep         bool `protobuf:"varint,5,opt,name=sweep,proto3" json:"sweep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFetchRequest) Reset() {
	*x = MFetchRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFetchRequest) ProtoMessage() {}

func (x *MFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFetchRequest.ProtoReflect.Descriptor instead.
func (*MFetchRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *MFetchRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *MFetchRequest) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *MFetchRequest) GetSlots() []int32 {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *MFetchRequest) GetFromSeqs() []uint64 {
	if x != nil {
		return x.FromSeqs
	}
	return nil
}

func (x *MFetchRequest) GetSweep() bool {
	if x != nil {
		return x.Sweep
	}
	return false
}

type MFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Items         []*FetchItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFetchResponse) Reset() {
	*x = MFetchResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFetchResponse) ProtoMessage() {}

func (x *MFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFetchResponse.ProtoReflect.Descriptor instead.
func (*MFetchResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{8}
}

func (x *MFetchResponse) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *MFetchResponse) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplicaProgressRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Follower string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	// Packed durable positions (from_seq = LEO+1), same shape as MFetch.
	Slots    []int32  `protobuf:"varint,2,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	FromSeqs []uint64 `protobuf:"varint,3,rep,packed,name=from_seqs,json=fromSeqs,proto3" json:"from_seqs,omitempty"`
	// stamp: refresh last-seen for every entry (liveness), not only moved
	// ones. False = record only positions that actually changed.
	Stamp         bool `protobuf:"varint,4,opt,name=stamp,proto3" json:"stamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaProgressRequest) Reset() {
	*x = ReplicaProgressRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaProgressRequest) ProtoMessage() {}

func (x *ReplicaProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaProgressRequest.ProtoReflect.Descriptor instead.
func (*ReplicaProgressRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicaProgressRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *ReplicaProgressRequest) GetSlots() []int32 {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ReplicaProgressRequest) GetFromSeqs() []uint64 {
	if x != nil {
		return x.FromSeqs
	}
	return nil
}

func (x *ReplicaProgressRequest) GetStamp() bool {
	if x != nil {
		return x.Stamp
	}
	return false
}

type ReplicaProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaProgressResponse) Reset() {
	*x = ReplicaProgressResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaProgressResponse) ProtoMessage() {}

func (x *ReplicaProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaProgressResponse.ProtoReflect.Descriptor instead.
func (*ReplicaProgressResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{10}
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // one encoded record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{11}
}

func (x *ReplicateRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReplicateRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReplicateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{12}
}

type SlotLeoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeoRequest) Reset() {
	*x = SlotLeoRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeoRequest) ProtoMessage() {}

func (x *SlotLeoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeoRequest.ProtoReflect.Descriptor instead.
func (*SlotLeoRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{13}
}

func (x *SlotLeoRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// SlotLeoResponse answers a slot's log end offset plus a summary of its
// aggregate directory, so a caller can tell whether this node holds a slot
// whose stream state is CONSISTENT with what its LEO claims.
//
// leo alone is not enough: a node can sit at a high LEO while some aggregate's
// stream is shorter, because the records above it were appended without the
// directory adopting their versions (DESIGN.md §1.1 rule 3). Comparing LEOs is
// then satisfied while records exist that no reader can serve. The three
// counters below make that state detectable in the same round trip:
//
//   - aggregates: directory entries (one per aggregate the slot holds)
//   - versions:   sum of the claimed latest version over those entries
//   - resolvable: sum of the seqs the directory can actually resolve
//
// versions == resolvable means every claimed version has a resolvable seq, so
// nothing is stranded in the WAL. A caller that needs "this node really holds
// everything up to leo" must check that equality, not just the offset.
type SlotLeoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leo           uint64                 `protobuf:"varint,1,opt,name=leo,proto3" json:"leo,omitempty"`
	Aggregates    uint64                 `protobuf:"varint,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`
	Versions      uint64                 `protobuf:"varint,3,opt,name=versions,proto3" json:"versions,omitempty"`
	Resolvable    uint64                 `protobuf:"varint,4,opt,name=resolvable,proto3" json:"resolvable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeoResponse) Reset() {
	*x = SlotLeoResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeoResponse) ProtoMessage() {}

func (x *SlotLeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeoResponse.ProtoReflect.Descriptor instead.
func (*SlotLeoResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{14}
}

func (x *SlotLeoResponse) GetLeo() uint64 {
	if x != nil {
		return x.Leo
	}
	return 0
}

func (x *SlotLeoResponse) GetAggregates() uint64 {
	if x != nil {
		return x.Aggregates
	}
	return 0
}

func (x *SlotLeoResponse) GetVersions() uint64 {
	if x != nil {
		return x.Versions
	}
	return 0
}

func (x *SlotLeoResponse) GetResolvable() uint64 {
	if x != nil {
		return x.Resolvable
	}
	return 0
}

// FenceSlotRequest freezes one migrating slot on its source leader. The reply
// carries the frozen LEO the target has confirmed.
type FenceSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceSlotRequest) Reset() {
	*x = FenceSlotRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceSlotRequest) ProtoMessage() {}

func (x *FenceSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceSlotRequest.ProtoReflect.Descriptor instead.
func (*FenceSlotRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{15}
}

func (x *FenceSlotRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type FenceSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leo           uint64                 `protobuf:"varint,1,opt,name=leo,proto3" json:"leo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceSlotResponse) Reset() {
	*x = FenceSlotResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceSlotResponse) ProtoMessage() {}

func (x *FenceSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceSlotResponse.ProtoReflect.Descriptor instead.
func (*FenceSlotResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{16}
}

func (x *FenceSlotResponse) GetLeo() uint64 {
	if x != nil {
		return x.Leo
	}
	return 0
}

// SlotLeaderRequest asks a peer for its local placement view of one slot.
type SlotLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeaderRequest) Reset() {
	*x = SlotLeaderRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeaderRequest) ProtoMessage() {}

func (x *SlotLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeaderRequest.ProtoReflect.Descriptor instead.
func (*SlotLeaderRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{17}
}

func (x *SlotLeaderRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// SlotLeaderResponse carries the peer's local leader ("" when unassigned) and
// the placement epoch, so the caller can tell "the target has applied the move"
// (leader == target, epoch >= the committed one) from a stale view.
type SlotLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        string                 `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotLeaderResponse) Reset() {
	*x = SlotLeaderResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLeaderResponse) ProtoMessage() {}

func (x *SlotLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLeaderResponse.ProtoReflect.Descriptor instead.
func (*SlotLeaderResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{18}
}

func (x *SlotLeaderResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *SlotLeaderResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// PushSegmentsRequest is one message of the snapshot stream: the first
// message of a file carries its name and total size (header bytes included),
// following messages carry data only. A new name starts a new file.
type PushSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // set on the first chunk of each segment file
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // total bytes of the file, set with name
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`  // file bytes; stream order, chunk sizes bounded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSegmentsRequest) Reset() {
	*x = PushSegmentsRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentsRequest) ProtoMessage() {}

func (x *PushSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentsRequest.ProtoReflect.Descriptor instead.
func (*PushSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{19}
}

func (x *PushSegmentsRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PushSegmentsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PushSegmentsRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PushSegmentsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSegmentsResponse) Reset() {
	*x = PushSegmentsResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentsResponse) ProtoMessage() {}

func (x *PushSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentsResponse.ProtoReflect.Descriptor instead.
func (*PushSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{20}
}

type TriggerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{21}
}

func (x *TriggerSnapshotRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TriggerSnapshotRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{22}
}

// DropSlotRequest asks a peer to discard its local copy of one slot (see the
// DropSlot RPC). node names the caller, for the target's log.
type DropSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropSlotRequest) Reset() {
	*x = DropSlotRequest{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSlotRequest) ProtoMessage() {}

func (x *DropSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSlotRequest.ProtoReflect.Descriptor instead.
func (*DropSlotRequest) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{23}
}

func (x *DropSlotRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DropSlotRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type DropSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropSlotResponse) Reset() {
	*x = DropSlotResponse{}
	mi := &file_pushupes_v1_peer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSlotResponse) ProtoMessage() {}

func (x *DropSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushupes_v1_peer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSlotResponse.ProtoReflect.Descriptor instead.
func (*DropSlotResponse) Descriptor() ([]byte, []int) {
	return file_pushupes_v1_peer_proto_rawDescGZIP(), []int{24}
}

var File_pushupes_v1_peer_proto protoreflect.FileDescriptor

const file_pushupes_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x16pushupes/v1/peer.proto\x12\vpushupes.v1\"\r\n" +
	"\vPingRequest\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"a\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"admin_addr\x18\x02 \x01(\tR\tadminAddr\x12\x1f\n" +
	"\vclient_addr\x18\x03 \x01(\tR\n" +
	"clientAddr\"\x12\n" +
	"\x10RegisterResponse\";\n" +
	"\fAdoptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpeer_addr\x18\x02 \x01(\tR\bpeerAddr\"\x0f\n" +
	"\rAdoptResponse\"o\n" +
	"\tFetchItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x04R\anextSeq\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x95\x01\n" +
	"\rMFetchRequest\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x03R\x06waitMs\x12\x18\n" +
	"\x05slots\x18\x03 \x03(\x05B\x02\x10\x01R\x05slots\x12\x1f\n" +
	"\tfrom_seqs\x18\x04 \x03(\x04B\x02\x10\x01R\bfromSeqs\x12\x14\n" +
	"\x05sweep\x18\x05 \x01(\bR\x05sweep\"Z\n" +
	"\x0eMFetchResponse\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.pushupes.v1.FetchItemR\x05items\"\x85\x01\n" +
	"\x16ReplicaProgressRequest\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12\x18\n" +
	"\x05slots\x18\x02 \x03(\x05B\x02\x10\x01R\x05slots\x12\x1f\n" +
	"\tfrom_seqs\x18\x03 \x03(\x04B\x02\x10\x01R\bfromSeqs\x12\x14\n" +
	"\x05stamp\x18\x04 \x01(\bR\x05stamp\"\x19\n" +
	"\x17ReplicaProgressResponse\"R\n" +
	"\x10ReplicateRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x13\n" +
	"\x11ReplicateResponse\"$\n" +
	"\x0eSlotLeoRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"\x7f\n" +
	"\x0fSlotLeoResponse\x12\x10\n" +
	"\x03leo\x18\x01 \x01(\x04R\x03leo\x12\x1e\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\x04R\n" +
	"aggregates\x12\x1a\n" +
	"\bversions\x18\x03 \x01(\x04R\bversions\x12\x1e\n" +
	"\n" +
	"resolvable\x18\x04 \x01(\x04R\n" +
	"resolvable\"&\n" +
	"\x10FenceSlotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"%\n" +
	"\x11FenceSlotResponse\x12\x10\n" +
	"\x03leo\x18\x01 \x01(\x04R\x03leo\"'\n" +
	"\x11SlotLeaderRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"B\n" +
	"\x12SlotLeaderResponse\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\tR\x06leader\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\"e\n" +
	"\x13PushSegmentsRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x16\n" +
	"\x14PushSegmentsResponse\"E\n" +
	"\x16TriggerSnapshotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\"\x19\n" +
	"\x17TriggerSnapshotResponse\"9\n" +
	"\x0fDropSlotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"\x12\n" +
	"\x10DropSlotResponse2\x9f\a\n" +
	"\vPeerService\x12;\n" +
	"\x04Ping\x12\x18.pushupes.v1.PingRequest\x1a\x19.pushupes.v1.PingResponse\x12G\n" +
	"\bRegister\x12\x1c.pushupes.v1.RegisterRequest\x1a\x1d.pushupes.v1.RegisterResponse\x12>\n" +
	"\x05Adopt\x12\x19.pushupes.v1.AdoptRequest\x1a\x1a.pushupes.v1.AdoptResponse\x12A\n" +
	"\x06MFetch\x12\x1a.pushupes.v1.MFetchRequest\x1a\x1b.pushupes.v1.MFetchResponse\x12\\\n" +
	"\x0fReplicaProgress\x12#.pushupes.v1.ReplicaProgressRequest\x1a$.pushupes.v1.ReplicaProgressResponse\x12J\n" +
	"\tReplicate\x12\x1d.pushupes.v1.ReplicateRequest\x1a\x1e.pushupes.v1.ReplicateResponse\x12D\n" +
	"\aSlotLeo\x12\x1b.pushupes.v1.SlotLeoRequest\x1a\x1c.pushupes.v1.SlotLeoResponse\x12J\n" +
	"\tFenceSlot\x12\x1d.pushupes.v1.FenceSlotRequest\x1a\x1e.pushupes.v1.FenceSlotResponse\x12M\n" +
	"\n" +
	"SlotLeader\x12\x1e.pushupes.v1.SlotLeaderRequest\x1a\x1f.pushupes.v1.SlotLeaderResponse\x12U\n" +
	"\fPushSegments\x12 .pushupes.v1.PushSegmentsRequest\x1a!.pushupes.v1.PushSegmentsResponse(\x01\x12\\\n" +
	"\x0fTriggerSnapshot\x12#.pushupes.v1.TriggerSnapshotRequest\x1a$.pushupes.v1.TriggerSnapshotResponse\x12G\n" +
	"\bDropSlot\x12\x1c.pushupes.v1.DropSlotRequest\x1a\x1d.pushupes.v1.DropSlotResponseB2Z0pushupes/internal/grpcapi/pushupes/v1;pushupesv1b\x06proto3"

var (
	file_pushupes_v1_peer_proto_rawDescOnce sync.Once
	file_pushupes_v1_peer_proto_rawDescData []byte
)

func file_pushupes_v1_peer_proto_rawDescGZIP() []byte {
	file_pushupes_v1_peer_proto_rawDescOnce.Do(func() {
		file_pushupes_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pushupes_v1_peer_proto_rawDesc), len(file_pushupes_v1_peer_proto_rawDesc)))
	})
	return file_pushupes_v1_peer_proto_rawDescData
}

var file_pushupes_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pushupes_v1_peer_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: pushupes.v1.PingRequest
	(*PingResponse)(nil),            // 1: pushupes.v1.PingResponse
	(*RegisterRequest)(nil),         // 2: pushupes.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 3: pushupes.v1.RegisterResponse
	(*AdoptRequest)(nil),            // 4: pushupes.v1.AdoptRequest
	(*AdoptResponse)(nil),           // 5: pushupes.v1.AdoptResponse
	(*FetchItem)(nil),               // 6: pushupes.v1.FetchItem
	(*MFetchRequest)(nil),           // 7: pushupes.v1.MFetchRequest
	(*MFetchResponse)(nil),          // 8: pushupes.v1.MFetchResponse
	(*ReplicaProgressRequest)(nil),  // 9: pushupes.v1.ReplicaProgressRequest
	(*ReplicaProgressResponse)(nil), // 10: pushupes.v1.ReplicaProgressResponse
	(*ReplicateRequest)(nil),        // 11: pushupes.v1.ReplicateRequest
	(*ReplicateResponse)(nil),       // 12: pushupes.v1.ReplicateResponse
	(*SlotLeoRequest)(nil),          // 13: pushupes.v1.SlotLeoRequest
	(*SlotLeoResponse)(nil),         // 14: pushupes.v1.SlotLeoResponse
	(*FenceSlotRequest)(nil),        // 15: pushupes.v1.FenceSlotRequest
	(*FenceSlotResponse)(nil),       // 16: pushupes.v1.FenceSlotResponse
	(*SlotLeaderRequest)(nil),       // 17: pushupes.v1.SlotLeaderRequest
	(*SlotLeaderResponse)(nil),      // 18: pushupes.v1.SlotLeaderResponse
	(*PushSegmentsRequest)(nil),     // 19: pushupes.v1.PushSegmentsRequest
	(*PushSegmentsResponse)(nil),    // 20: pushupes.v1.PushSegmentsResponse
	(*TriggerSnapshotRequest)(nil),  // 21: pushupes.v1.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil), // 22: pushupes.v1.TriggerSnapshotResponse
	(*DropSlotRequest)(nil),         // 23: pushupes.v1.DropSlotRequest
	(*DropSlotResponse)(nil),        // 24: pushupes.v1.DropSlotResponse
}
var file_pushupes_v1_peer_proto_depIdxs = []int32{
	6,  // 0: pushupes.v1.MFetchResponse.items:type_name -> pushupes.v1.FetchItem
	0,  // 1: pushupes.v1.PeerService.Ping:input_type -> pushupes.v1.PingRequest
	2,  // 2: pushupes.v1.PeerService.Register:input_type -> pushupes.v1.RegisterRequest
	4,  // 3: pushupes.v1.PeerService.Adopt:input_type -> pushupes.v1.AdoptRequest
	7,  // 4: pushupes.v1.PeerService.MFetch:input_type -> pushupes.v1.MFetchRequest
	9,  // 5: pushupes.v1.PeerService.ReplicaProgress:input_type -> pushupes.v1.ReplicaProgressRequest
	11, // 6: pushupes.v1.PeerService.Replicate:input_type -> pushupes.v1.ReplicateRequest
	13, // 7: pushupes.v1.PeerService.SlotLeo:input_type -> pushupes.v1.SlotLeoRequest
	15, // 8: pushupes.v1.PeerService.FenceSlot:input_type -> pushupes.v1.FenceSlotRequest
	17, // 9: pushupes.v1.PeerService.SlotLeader:input_type -> pushupes.v1.SlotLeaderRequest
	19, // 10: pushupes.v1.PeerService.PushSegments:input_type -> pushupes.v1.PushSegmentsRequest
	21, // 11: pushupes.v1.PeerService.TriggerSnapshot:input_type -> pushupes.v1.TriggerSnapshotRequest
	23, // 12: pushupes.v1.PeerService.DropSlot:input_type -> pushupes.v1.DropSlotRequest
	1,  // 13: pushupes.v1.PeerService.Ping:output_type -> pushupes.v1.PingResponse
	3,  // 14: pushupes.v1.PeerService.Register:output_type -> pushupes.v1.RegisterResponse
	5,  // 15: pushupes.v1.PeerService.Adopt:output_type -> pushupes.v1.AdoptResponse
	8,  // 16: pushupes.v1.PeerService.MFetch:output_type -> pushupes.v1.MFetchResponse
	10, // 17: pushupes.v1.PeerService.ReplicaProgress:output_type -> pushupes.v1.ReplicaProgressResponse
	12, // 18: pushupes.v1.PeerService.Replicate:output_type -> pushupes.v1.ReplicateResponse
	14, // 19: pushupes.v1.PeerService.SlotLeo:output_type -> pushupes.v1.SlotLeoResponse
	16, // 20: pushupes.v1.PeerService.FenceSlot:output_type -> pushupes.v1.FenceSlotResponse
	18, // 21: pushupes.v1.PeerService.SlotLeader:output_type -> pushupes.v1.SlotLeaderResponse
	20, // 22: pushupes.v1.PeerService.PushSegments:output_type -> pushupes.v1.PushSegmentsResponse
	22, // 23: pushupes.v1.PeerService.TriggerSnapshot:output_type -> pushupes.v1.TriggerSnapshotResponse
	24, // 24: pushupes.v1.PeerService.DropSlot:output_type -> pushupes.v1.DropSlotResponse
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pushupes_v1_peer_proto_init() }
func file_pushupes_v1_peer_proto_init() {
	if File_pushupes_v1_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pushupes_v1_peer_proto_rawDesc), len(file_pushupes_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pushupes_v1_peer_proto_goTypes,
		DependencyIndexes: file_pushupes_v1_peer_proto_depIdxs,
		MessageInfos:      file_pushupes_v1_peer_proto_msgTypes,
	}.Build()
	File_pushupes_v1_peer_proto = out.File
	file_pushupes_v1_peer_proto_goTypes = nil
	file_pushupes_v1_peer_proto_depIdxs = nil
}
